<a href="https://colab.research.google.com/github/Igirisu861/SmartDataProcessing/blob/main/NumpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Introduction**

# **Methods for array creation**

### **Array method**

In [2]:
import numpy as np

myList = [1,2,3]
#how to create an array from a list
arr = np.array(myList)
arr

array([1, 2, 3])

In [ ]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### **Arange method**

In [ ]:
#options for creating arrays
#arange will generate an array starting from the first parameter to until before the 2nd parameter
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#It also works without 2nd parameter
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#or you can add a step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### **Zeros method**

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
#create a 2 dimensional array
#the inner parentheses are a tuple of 5 rows and 6 columns
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### **Array of ones**

This method creates an array filled with number 1s

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

### **Linspace method**

This method creates an array within a range of numbers and is separated by the same distance between numbers. This is called *equidistance*.

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

### **Identity matrix**

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# **Generate random numbers**

 ### **Random generation with uniform distribuition**

It uses .rand

In [ ]:
np.random.rand(5)

array([0.15622038, 0.88143117, 0.90866851, 0.51846183, 0.73682632])

### **Random with normal (or gaussian) distribuition**

It uses randn

In [ ]:
np.random.randn(4,5)

array([[-0.78754639, -0.73908381,  0.73340834, -0.30965793,  0.80941864],
       [-0.19150106,  0.45188732, -0.14360139, -0.35835217,  1.46409483],
       [-1.25840858, -0.85834777, -0.05981215, -0.09217275, -0.91131805],
       [-0.78467305, -0.40869505, -0.17284484,  0.88869596, -0.65419686]])

### **Generate random integers**

Here the last parameter is the size of the array and the first two parameters are the range.

In [ ]:
np.random.randint(1,100,10)

array([55, 22, 14, 85, 44, 57, 79, 27, 17, 92])

# **Array manipulation methods**

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### **Reshape method**

It shapes the array in a specific set of rows and columns (if possible)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#for making the reshape permanent, remember to reassign the variable

arr2 = arr.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### **Max function**

it will give you the max number of the array

In [ ]:
randomArr = np.random.randint(0,50,10)
randomArr

array([19, 20, 39, 38, 18, 25,  6,  4, 29, 35])

In [ ]:
randomArr.max()

46

### **Min function**

returns the smallest number in the array

In [ ]:
randomArr.min()

### **Argmax and argmin functions**
These functions return the maximum or minimum numbers index in a determined axis

In [ ]:
randomArr.argmax()

2

In [ ]:
randomArr.argmin()

7

### **Array indexing**

In [4]:
arr3 = np.random.randn(10)
arr3

array([-0.51842027,  0.60453781, -0.67454127, -0.54903418, -0.16126668,
        0.21573577,  0.85993423, -0.59398931, -0.74948315,  1.11023996])

This returns the number in the 8th position in the array

In [ ]:
arr3[8]

-0.4331124710106967

This returns from the 2nd position to the 5th

In [ ]:
arr3[2:6]

array([-0.26087263, -1.17165005,  0.87559636, -0.55822636])

This returns from the beginning until before the 2nd parameter

In [ ]:
arr3[:5]

array([-1.86898272,  0.48627151, -0.26087263, -1.17165005,  0.87559636])

### **Broadcasting**

Modify values in a set range

In [ ]:
arr3[4:6]= 0.99
arr3

array([-1.86898272,  0.48627151, -0.26087263, -1.17165005,  0.99      ,
        0.99      ,  0.25354576,  0.04655468, -0.43311247,  0.9953302 ])

### **Slicing**

Taking a piece of an array within a certain range

In [6]:
arr4 = np.random.rand(20)
arr4

array([4.83778463e-01, 1.12642341e-01, 3.59099910e-01, 2.91227500e-01,
       3.23780552e-01, 8.29779765e-01, 3.22164776e-01, 8.34083140e-01,
       2.47895298e-01, 3.69258325e-01, 1.12275971e-01, 6.35096027e-01,
       3.83101761e-01, 4.20921008e-01, 7.22522893e-03, 7.78863274e-01,
       1.73686434e-01, 7.08743610e-01, 8.91273430e-05, 8.03366654e-01])

In [7]:
sliceOfArr4= arr4[0:5]
sliceOfArr4

array([0.48377846, 0.11264234, 0.35909991, 0.2912275 , 0.32378055])

### **Broadcast to the slice**

In [8]:
sliceOfArr4[:] = 0.99
sliceOfArr4

array([0.99, 0.99, 0.99, 0.99, 0.99])

In [ ]:
arr4

array([0.99      , 0.99      , 0.99      , 0.99      , 0.99      ,
       0.45508806, 0.73986855, 0.23267028, 0.05713389, 0.18894023,
       0.61357266, 0.50950467, 0.07933199, 0.55565342, 0.75725854,
       0.8315215 , 0.56265955, 0.63321938, 0.84376856, 0.09792699])

For saving memory, Python also modifies the original array when changing the slice from it. For avoiding this, the OG array should be copied.

## **Two-Dimensional Arrays**

In [10]:
arr2d = np.random.randint(0,11,(3,4))
arr2d

array([[10,  9,  9,  5],
       [ 0,  4,  3,  4],
       [ 6,  2,  9,  4]])

### **Single bracket notation**

In [11]:
arr2d[2,3]

4

### **Double bracket notation**

In [ ]:
arr2d[2][2]

7

### **Slice notation**

The first parameter extracts the rows in range and the 2nd one extracts the columns in range (in this case from 1 and on)

In [ ]:
arr2d[0:2,1:]

array([[1, 3, 1],
       [6, 6, 1]])

# **Practice time!**

In [ ]:
import random
np.random.seed(42)
arr_2d = np.random.randint(0,100,12)
arr_2d

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99])

In [ ]:
arr_2d = arr_2d.reshape(4,3)
arr_2d

array([[51, 92, 14],
       [71, 60, 20],
       [82, 86, 74],
       [74, 87, 99]])

Extract 60, 20, 86, and 74 from the matrix using slice notation

In [ ]:
arr2d_slice = arr_2d[1:3,1:]
arr2d_slice

array([[60, 20],
       [86, 74]])

## **Conditional selection**

In [ ]:
boolArr = arr_2d > 45
boolArr

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr_2d[boolArr]

array([51, 92, 71, 60, 82, 86, 74, 74, 87, 99])

In [ ]:
arr_2d[arr_2d<70]

array([51, 14, 60, 20])